/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "glitch-1": {
          "0%": { clipPath: "inset(20% 0 60% 0)" },
          "5%": { clipPath: "inset(60% 0 10% 0)" },
          "10%": { clipPath: "inset(10% 0 80% 0)" },
          "15%": { clipPath: "inset(80% 0 5% 0)" },
          "20%": { clipPath: "inset(40% 0 30% 0)" },
          "25%": { clipPath: "inset(5% 0 90% 0)" },
          "30%": { clipPath: "inset(70% 0 15% 0)" },
          "35%": { clipPath: "inset(25% 0 50% 0)" },
          "40%": { clipPath: "inset(90% 0 3% 0)" },
          "45%": { clipPath: "inset(15% 0 70% 0)" },
          "50%": { clipPath: "inset(55% 0 20% 0)" },
          "55%": { clipPath: "inset(30% 0 45% 0)" },
          "60%": { clipPath: "inset(85% 0 8% 0)" },
          "65%": { clipPath: "inset(8% 0 85% 0)" },
          "70%": { clipPath: "inset(50% 0 25% 0)" },
          "75%": { clipPath: "inset(20% 0 65% 0)" },
          "80%": { clipPath: "inset(75% 0 12% 0)" },
          "85%": { clipPath: "inset(35% 0 40% 0)" },
          "90%": { clipPath: "inset(95% 0 2% 0)" },
          "95%": { clipPath: "inset(12% 0 78% 0)" },
          "100%": { clipPath: "inset(45% 0 30% 0)" },
        },
        "glitch-2": {
          "0%": { clipPath: "inset(65% 0 15% 0)" },
          "5%": { clipPath: "inset(15% 0 70% 0)" },
          "10%": { clipPath: "inset(85% 0 5% 0)" },
          "15%": { clipPath: "inset(5% 0 85% 0)" },
          "20%": { clipPath: "inset(50% 0 30% 0)" },
          "25%": { clipPath: "inset(25% 0 60% 0)" },
          "30%": { clipPath: "inset(70% 0 20% 0)" },
          "35%": { clipPath: "inset(10% 0 80% 0)" },
          "40%": { clipPath: "inset(45% 0 35% 0)" },
          "45%": { clipPath: "inset(90% 0 5% 0)" },
          "50%": { clipPath: "inset(30% 0 55% 0)" },
          "55%": { clipPath: "inset(75% 0 10% 0)" },
          "60%": { clipPath: "inset(20% 0 65% 0)" },
          "65%": { clipPath: "inset(55% 0 25% 0)" },
          "70%": { clipPath: "inset(5% 0 90% 0)" },
          "75%": { clipPath: "inset(80% 0 8% 0)" },
          "80%": { clipPath: "inset(35% 0 45% 0)" },
          "85%": { clipPath: "inset(60% 0 20% 0)" },
          "90%": { clipPath: "inset(15% 0 75% 0)" },
          "95%": { clipPath: "inset(50% 0 35% 0)" },
          "100%": { clipPath: "inset(25% 0 60% 0)" },
        },
        "scroll": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "glitch-1": "glitch-1 2.5s infinite linear alternate",
        "glitch-2": "glitch-2 2.5s infinite linear alternate",
        "scroll": "scroll 30s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}